team3_app/config/routes.rb
Rails.application.routes.draw do
  resources :movie_reviews
  get 'users/show'
  devise_for :users
  resources :songs
  resources :movies
  root  'static_pages#home'
  get   '/about',   to: 'static_pages#about'
  get   '/contact', to: 'static_pages#contact'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

team3_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

team3_app/app/models/movie.rb
class Movie < ApplicationRecord
    has_many :movie_review, -> { order "created_at DESC"}
end

team3_app/app/models/movie_review.rb
class MovieReview < ApplicationRecord
    belongs_to :movie
    belongs_to :user
end

team3_app/app/models/song.rb
class Song < ApplicationRecord
end

team3_app/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one_attached :avatar
  has_many :movie_review, -> { order "created_at DESC"}
  
  validates :name, presence: true
  validates :age, presence: true
end

team3_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    protected
        def configure_permitted_parameters
            devise_parameter_sanitizer.permit :sign_up, keys: [:name, :age, :avatar]
            devise_parameter_sanitizer.permit :account_update, keys: [:name, :age, :avatar]
        end
end

team3_app/app/controllers/movie_reviews_controller.rb
class MovieReviewsController < ApplicationController
  before_action :set_movie_review, only: [:show, :edit, :update, :destroy]

  # GET /movie_reviews
  # GET /movie_reviews.json
  def index
    @movie_reviews = MovieReview.all
  end

  # GET /movie_reviews/1
  # GET /movie_reviews/1.json
  def show
  end

  # GET /movie_reviews/new
  def new
    @movie_review = MovieReview.new
  end

  # GET /movie_reviews/1/edit
  def edit
  end

  # POST /movie_reviews
  # POST /movie_reviews.json
  def create
    @movie_review = MovieReview.new(movie_review_params)

    respond_to do |format|
      if @movie_review.save
        format.html { redirect_to @movie_review, notice: 'Movie review was successfully created.' }
        format.json { render :show, status: :created, location: @movie_review }
      else
        format.html { render :new }
        format.json { render json: @movie_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movie_reviews/1
  # PATCH/PUT /movie_reviews/1.json
  def update
    respond_to do |format|
      if @movie_review.update(movie_review_params)
        format.html { redirect_to @movie_review, notice: 'Movie review was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie_review }
      else
        format.html { render :edit }
        format.json { render json: @movie_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movie_reviews/1
  # DELETE /movie_reviews/1.json
  def destroy
    @movie_review.destroy
    respond_to do |format|
      format.html { redirect_to movie_reviews_url, notice: 'Movie review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie_review
      @movie_review = MovieReview.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_review_params
      params.require(:movie_review).permit(:user_id, :movie_id, :review)
    end
end

team3_app/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @movie_review = MovieReview.new
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:name, :length, :content)
    end
end

team3_app/app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
    @song = Song.new  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def song_params
      params.require(:song).permit(:song_name, :singer_name)
    end
end

team3_app/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

team3_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end
end

team3_app/app/helpers/application_helper.rb
module ApplicationHelper
end

team3_app/app/helpers/movie_reviews_helper.rb
module MovieReviewsHelper
end

team3_app/app/helpers/movies_helper.rb
module MoviesHelper
end

team3_app/app/helpers/songs_helper.rb
module SongsHelper
end

team3_app/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

team3_app/app/helpers/users_helper.rb
module UsersHelper
end

team3_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Team3App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to "ホーム", root_path %>
    <%= link_to "約", about_path %>
    <%= link_to "連絡先", contact_path %>
    <% if user_signed_in? %>
    <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
    <%= link_to current_user.name, users_show_path %></p>
    <% else %>
    <%= link_to "サインイン", new_user_session_path %>
    <%= link_to "ユーザ登録", new_user_registration_path %>
    <% end %>
    <hr>
    <%= yield %>
  </body>
</html>

team3_app/app/views/movie_reviews/_form.html.erb
<%= form_with(model: movie_review, local: true) do |form| %>
  <% if movie_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie_review.errors.count, "error") %> prohibited this movie_review from being saved:</h2>

      <ul>
        <% movie_review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :movie_id %>
    <%= form.number_field :movie_id %>
  </div>

  <div class="field">
    <%= form.label :review %>
    <%= form.text_area :review %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

team3_app/app/views/movie_reviews/edit.html.erb
<h1>Editing Movie Review</h1>

<%= render 'form', movie_review: @movie_review %>

<%= link_to 'Show', @movie_review %> |
<%= link_to 'Back', movie_reviews_path %>

team3_app/app/views/movie_reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movie Reviews</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Movie</th>
      <th>Review</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movie_reviews.each do |movie_review| %>
      <tr>
        <td><%= movie_review.user_id %></td>
        <td><%= movie_review.movie_id %></td>
        <td><%= movie_review.review %></td>
        <td><%= link_to 'Show', movie_review %></td>
        <td><%= link_to 'Edit', edit_movie_review_path(movie_review) %></td>
        <td><%= link_to 'Destroy', movie_review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie Review', new_movie_review_path %>
<%= link_to 'Movie list', movies_path %>

team3_app/app/views/movie_reviews/new.html.erb
<h1>New Movie Review</h1>

<%= render 'form', movie_review: @movie_review %>

<%= link_to 'Back', movie_reviews_path %>

team3_app/app/views/movie_reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @movie_review.user_id %>
</p>

<p>
  <strong>Movie:</strong>
  <%= @movie_review.movie_id %>
</p>

<p>
  <strong>Review:</strong>
  <%= @movie_review.review %>
</p>

<%= link_to 'Edit', edit_movie_review_path(@movie_review) %> |
<%= link_to 'Back', movie_reviews_path %>

team3_app/app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :length %>
    <%= form.time_select :length %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

team3_app/app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

team3_app/app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Length</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.name %></td>
        <td><%= movie.length.strftime("%k:%M") %></td>
        <td><%= movie.content %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

team3_app/app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

team3_app/app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @movie.name %>
</p>

<p>
  <strong>Length:</strong>
  <%= @movie.length.strftime("%k:%M") %>
</p>

<p>
  <strong>Content:</strong>
  <%= @movie.content %>
</p>

<h3>Review List</h3>
  <ul>
    <% @movie.movie_review.each do |movie_review|%>
      <li><%= movie_review.review %>
      (<%= movie_review.user.name %>)</li>
    <% end %>
  </ul>
  
<%= form_with(model: @movie_review, local: true) do |form| %>
    <%= form.hidden_field :user_id, :value => current_user.id %>
    <%= form.hidden_field :movie_id, :value => @movie.id %>

  <div class="field">
    <%= form.label :review %>
    <%= form.text_area :review %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'SHOW OST',songs_path%>|
<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>

team3_app/app/views/songs/_form.html.erb
<%= form_with(model: song, local: true) do |form| %>
  <% if song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
        <% song.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :song_name %>
    <%= form.text_area :song_name %>
  </div>

  <div class="field">
    <%= form.label :singer_name %>
    <%= form.text_area :singer_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

team3_app/app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

team3_app/app/views/songs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Songs</h1>

<table>
  <thead>
    <tr>
      <th>Song name</th>
      <th>Singer name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.song_name %></td>
        <td><%= song.singer_name %></td>
        <td><%= link_to 'Show', song %></td>
        <td><%= link_to 'Edit', edit_song_path(song) %></td>
        <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Song', new_song_path %>

team3_app/app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Back', songs_path %>

team3_app/app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Song name:</strong>
  <%= @song.song_name %>
</p>

<p>
  <strong>Singer name:</strong>
  <%= @song.singer_name %>
</p>

<%= link_to 'Edit' %> |
<%= link_to 'Back', movies_path %>

team3_app/app/views/static_pages/about.html.erb
<h1>About</h1>
<p>チーム３</p>
<p>Dương Văn Đức - 20176724</p>
<p>Đàm Tiến Đạt - 20176713</p>
<p>Lê Huy Hoàng - 20176767</p>
<p>Đoàn Ngọc Chiến - 20176701</p>
<p>Hoàng Thành Lâm - 20176798</p>

team3_app/app/views/static_pages/contact.html.erb
<h1>Contact</h1>
<p></p>

team3_app/app/views/static_pages/home.html.erb
<h1>Welcome</h1>
<%= link_to "映画一覧をみる", movies_path %>

team3_app/app/views/users/show.html.erb
<h1>プロフィール</h1>

<p>
  <% if @user.avatar.attached? %>
    <%= image_tag @user.avatar %>
  <% end %>
</p>

<h3>名前</h3>
<%= @user.name %>

<h3>年齢</h3>
<%= @user.age %>

<h3>メールアドレス</h3>
<%= @user.email %> 
<br>
<%= link_to "edit", edit_user_registration_path %>